---
- name: reload firewall
  ufw:
    state: reloaded
  become: yes

- name: reload systemd
  systemd:
    daemon_reload: yes
  become: yes

- name: Restart MinIO
  systemd:
    name: minio
    state: restarted
  become: yes

